### ISSUE TITLE
Uncaught Exception When Logging In

### ISSUE THREAD

**Issue by derekr** [drudge/gist.chocmixin#1]
Getting the following error in a console window when trying to login:

```
Error: /Users/dreynolds/Library/Application Support/Chocolat/Mixins/gist.chocmixin/init.js
on line 129 (column 20) of Uncaught TypeError: Object [object Object] has no method 'evalExpr'
```

**Comment by derekr** [comment]
![Screen](http://f.cl.ly/items/3W3J3K3x33283b3u3a1g/Screen%20Shot%202012-08-23%20at%201.47.28%20PM.png)

**Comment by drudge** [comment]
Looks like you are on an old build of Chocolat. Try http://files.fileability.net/Chocolat_node4.zip

**Comment by derekr** [comment]
Yeah I had node3. I thought that was it, but I couldn't get a new build. Thanks!
