### ISSUE TITLE
Could not complete requested action

### ISSUE THREAD

**Issue by carlpoole** [drudge/gist.chocmixin#3]
Hi there. I keep getting error to check credentials and try again even though they are correct. I triple checked.

Version 2.2.3

Thanks for your help!

**Comment by drudge** [comment]
@carlpoole Thanks for reporting it. It looks like github changed their rules and [require a user-agent now](http://developer.github.com/v3/#user-agent-required). I've fixed it and the update should be available with the `Install Mixins...` window of Chocolat.

**Comment by carlpoole** [comment]
Awesome, thank you, sir!
